/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebButton {
        /**
          * Define the color of the button (e.g., 'indigo', 'blue', 'red')
         */
        "color": string;
        /**
          * Define the size of the button (e.g., 'small', 'medium', 'large')
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Define the button type (e.g., 'button', 'submit', 'reset')
         */
        "type": 'button' | 'submit' | 'reset';
    }
}
declare global {
    interface HTMLWebButtonElement extends Components.WebButton, HTMLStencilElement {
    }
    var HTMLWebButtonElement: {
        prototype: HTMLWebButtonElement;
        new (): HTMLWebButtonElement;
    };
    interface HTMLElementTagNameMap {
        "web-button": HTMLWebButtonElement;
    }
}
declare namespace LocalJSX {
    interface WebButton {
        /**
          * Define the color of the button (e.g., 'indigo', 'blue', 'red')
         */
        "color"?: string;
        /**
          * Define the size of the button (e.g., 'small', 'medium', 'large')
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Define the button type (e.g., 'button', 'submit', 'reset')
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface IntrinsicElements {
        "web-button": WebButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "web-button": LocalJSX.WebButton & JSXBase.HTMLAttributes<HTMLWebButtonElement>;
        }
    }
}
